In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
fileBase="./yearlyData/PlannerPropReg"
num_of_repetitions = 100

In [3]:
yearlyDataAV=np.zeros((20,100))
yearlyDataCo=np.zeros((20,100))
yearlyDataIn=np.zeros((20,100))

In [4]:
for y in range(num_of_repetitions):
    yearlyData=np.load(fileBase+str(y)+".npy")
    yearlyDataAV[:,y]=yearlyData[:,0]
    yearlyDataCo[:,y]=yearlyData[:,1]
    yearlyDataIn[:,y]=yearlyData[:,2]    

In [5]:
yearlyDataAV

array([[1233399.18194448, 1268685.48194448, 1247560.84444448, ...,
        1245215.26250004, 1280892.72500004, 1271538.29444448],
       [1306027.09444448, 1292731.78472226, 1285282.60833337, ...,
        1297439.50277782, 1320859.91111115, 1302320.05277782],
       [1341059.35694448, 1357056.43472226, 1358361.01944448, ...,
        1348811.83888893, 1338155.88472226, 1339515.92500004],
       ...,
       [1710891.11250005, 1686883.59166671, 1695649.47777782, ...,
        1676651.77777782, 1721970.50000005, 1715294.22361116],
       [1702047.49861116, 1711977.50277783, 1741069.70972227, ...,
        1712128.07916671, 1733018.17222227, 1745633.43194449],
       [1746562.85694449, 1742846.69166672, 1760066.49583338, ...,
        1663048.89722227, 1739947.81111116, 1711397.1930556 ]])

In [6]:
yearlyDataCo

array([[ 714183.71435053,  748192.0204229 ,  737460.13008838, ...,
         744858.69569856,  748429.46892735,  727984.67160228],
       [ 760303.31016728,  741963.31653268,  747490.22654524, ...,
         759870.85142681,  777305.759957  ,  782899.67630073],
       [ 782138.87218889,  798193.48010228,  790547.53123561, ...,
         769444.23134645,  777532.69581566,  763107.40986231],
       ...,
       [1049062.76281234, 1049729.62401696, 1077587.09351731, ...,
        1051503.52954921, 1062679.85732659, 1050713.76570269],
       [1088038.38494301, 1065517.84565088, 1089525.69693704, ...,
        1057934.85020271, 1079784.39251566, 1112294.67287173],
       [1090126.63402074, 1065533.43654102, 1077454.70130672, ...,
        1058160.669154  , 1070243.61176469, 1076434.75685909]])

In [7]:
yearlyDataIn

array([[508814.18474816, 526077.84497195, 505855.01033114, ...,
        515939.32690546, 532623.55719124, 512523.21602247],
       [555946.2508313 , 543422.51078248, 535657.06425747, ...,
        530496.32730994, 550182.86698845, 546325.67793771],
       [567337.03272692, 555444.08622393, 568721.07273058, ...,
        571755.11153689, 557193.61420638, 547114.21717422],
       ...,
       [700261.44337547, 640358.88001514, 620319.21895646, ...,
        636386.22425753, 647539.43240986, 643166.72725203],
       [615364.78422917, 645374.01431324, 645056.30652909, ...,
        644199.46628404, 668233.2368561 , 667941.46145201],
       [635616.98940256, 653852.26942569, 675810.23146829, ...,
        616097.73021695, 647690.36905612, 638381.15481997]])

In [8]:
results=np.zeros((20,9))

In [9]:
for i in range(20):
    results[i,0]=yearlyDataAV[i,:].mean()
    results[i,1]=yearlyDataAV[i,:].mean()+2*yearlyDataAV[i,:].std()
    results[i,2]=yearlyDataAV[i,:].mean()-2*yearlyDataAV[i,:].std()
    results[i,3]=yearlyDataCo[i,:].mean()
    results[i,4]=yearlyDataCo[i,:].mean()+2*yearlyDataCo[i,:].std()
    results[i,5]=yearlyDataCo[i,:].mean()-2*yearlyDataCo[i,:].std()
    results[i,6]=yearlyDataIn[i,:].mean()
    results[i,7]=yearlyDataIn[i,:].mean()+2*yearlyDataIn[i,:].std()
    results[i,8]=yearlyDataIn[i,:].mean()-2*yearlyDataIn[i,:].std()

In [10]:
#results

In [34]:
plt.suptitle("Yearly National Accounts PlannerPropReg1")
plt.plot(results[:,0],color='darkorange',linewidth=1,label="added value")
plt.plot(results[:,1],color='darkorange',linestyle='dotted',linewidth=1,label="added value + 2std")
plt.plot(results[:,2],color='darkorange',linestyle='dashed',linewidth=1,label="added value - 2std")
plt.plot(results[:,3],color='green',linewidth=1,label="consumptions")
plt.plot(results[:,4],color='green',linestyle='dotted',linewidth=1,label="consumptions + 2std")
plt.plot(results[:,5],color='green',linestyle='dashed',linewidth=1,label="consumptions - 2std")
plt.plot(results[:,6],color='red',linewidth=1,label="investments")
plt.plot(results[:,7],color='red',linestyle='dotted',linewidth=1,label="investments + 2std")
plt.plot(results[:,8],color='red',linestyle='dashed',linewidth=1,label="investments - 2std")
plt.plot(0)
plt.xlabel("Years")
plt.legend(bbox_to_anchor=(1, 1), loc='upper left', ncol=1)
plt.savefig("_YearlyNationalAccountsReg.jpg", dpi=180, bbox_inches='tight')